package dvdrental;
// Generated Apr 30, 2017 1:09:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer cartId;
     private Date creationDate;
     private boolean checkedOut;
     private short customerId;
     private Set cartofitemses = new HashSet(0);

    public Cart() {
    }

	
    public Cart(Date creationDate, boolean checkedOut, short customerId) {
        this.creationDate = creationDate;
        this.checkedOut = checkedOut;
        this.customerId = customerId;
    }
    public Cart(Date creationDate, boolean checkedOut, short customerId, Set cartofitemses) {
       this.creationDate = creationDate;
       this.checkedOut = checkedOut;
       this.customerId = customerId;
       this.cartofitemses = cartofitemses;
    }
   
    public Integer getCartId() {
        return this.cartId;
    }
    
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public boolean isCheckedOut() {
        return this.checkedOut;
    }
    
    public void setCheckedOut(boolean checkedOut) {
        this.checkedOut = checkedOut;
    }
    public short getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(short customerId) {
        this.customerId = customerId;
    }
    public Set getCartofitemses() {
        return this.cartofitemses;
    }
    
    public void setCartofitemses(Set cartofitemses) {
        this.cartofitemses = cartofitemses;
    }




}


