package dvdrental;
// Generated Apr 30, 2017 1:09:30 AM by Hibernate Tools 4.3.1



/**
 * CartofitemsId generated by hbm2java
 */
public class CartofitemsId  implements java.io.Serializable {


     private int cartItemId;
     private int cartId;

    public CartofitemsId() {
    }

    public CartofitemsId(int cartItemId, int cartId) {
       this.cartItemId = cartItemId;
       this.cartId = cartId;
    }
   
    public int getCartItemId() {
        return this.cartItemId;
    }
    
    public void setCartItemId(int cartItemId) {
        this.cartItemId = cartItemId;
    }
    public int getCartId() {
        return this.cartId;
    }
    
    public void setCartId(int cartId) {
        this.cartId = cartId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CartofitemsId) ) return false;
		 CartofitemsId castOther = ( CartofitemsId ) other; 
         
		 return (this.getCartItemId()==castOther.getCartItemId())
 && (this.getCartId()==castOther.getCartId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCartItemId();
         result = 37 * result + this.getCartId();
         return result;
   }   


}


