package dvdrental;
// Generated Apr 30, 2017 1:09:30 AM by Hibernate Tools 4.3.1



/**
 * Cartofitems generated by hbm2java
 */
public class Cartofitems  implements java.io.Serializable {


     private CartofitemsId id;
     private Cart cart;
     private short filmId;

    public Cartofitems() {
    }

    public Cartofitems(CartofitemsId id, Cart cart, short filmId) {
       this.id = id;
       this.cart = cart;
       this.filmId = filmId;
    }
   
    public CartofitemsId getId() {
        return this.id;
    }
    
    public void setId(CartofitemsId id) {
        this.id = id;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public short getFilmId() {
        return this.filmId;
    }
    
    public void setFilmId(short filmId) {
        this.filmId = filmId;
    }




}


