package dvdrental;
// Generated Apr 30, 2017 1:09:30 AM by Hibernate Tools 4.3.1



/**
 * FilmCategoryId generated by hbm2java
 */
public class FilmCategoryId  implements java.io.Serializable {


     private short filmId;
     private byte categoryId;

    public FilmCategoryId() {
    }

    public FilmCategoryId(short filmId, byte categoryId) {
       this.filmId = filmId;
       this.categoryId = categoryId;
    }
   
    public short getFilmId() {
        return this.filmId;
    }
    
    public void setFilmId(short filmId) {
        this.filmId = filmId;
    }
    public byte getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(byte categoryId) {
        this.categoryId = categoryId;
    }




}


