package dvdrental;
// Generated Apr 30, 2017 1:09:30 AM by Hibernate Tools 4.3.1



/**
 * FilmActorId generated by hbm2java
 */
public class FilmActorId  implements java.io.Serializable {


     private short actorId;
     private short filmId;

    public FilmActorId() {
    }

    public FilmActorId(short actorId, short filmId) {
       this.actorId = actorId;
       this.filmId = filmId;
    }
   
    public short getActorId() {
        return this.actorId;
    }
    
    public void setActorId(short actorId) {
        this.actorId = actorId;
    }
    public short getFilmId() {
        return this.filmId;
    }
    
    public void setFilmId(short filmId) {
        this.filmId = filmId;
    }




}


