package dvdrental;
// Generated Apr 30, 2017 1:09:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Wishlist generated by hbm2java
 */
public class Wishlist  implements java.io.Serializable {


     private Integer wishListId;
     private Date creationDate;
     private short customerId;
     private Set wishlistitemses = new HashSet(0);

    public Wishlist() {
    }

	
    public Wishlist(Date creationDate, short customerId) {
        this.creationDate = creationDate;
        this.customerId = customerId;
    }
    public Wishlist(Date creationDate, short customerId, Set wishlistitemses) {
       this.creationDate = creationDate;
       this.customerId = customerId;
       this.wishlistitemses = wishlistitemses;
    }
   
    public Integer getWishListId() {
        return this.wishListId;
    }
    
    public void setWishListId(Integer wishListId) {
        this.wishListId = wishListId;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public short getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(short customerId) {
        this.customerId = customerId;
    }
    public Set getWishlistitemses() {
        return this.wishlistitemses;
    }
    
    public void setWishlistitemses(Set wishlistitemses) {
        this.wishlistitemses = wishlistitemses;
    }




}


