package dvdrental;
// Generated Apr 30, 2017 1:09:30 AM by Hibernate Tools 4.3.1



/**
 * Wishlistitems generated by hbm2java
 */
public class Wishlistitems  implements java.io.Serializable {


     private Integer wishItemsId;
     private Wishlist wishlist;
     private short filmId;

    public Wishlistitems() {
    }

    public Wishlistitems(Wishlist wishlist, short filmId) {
       this.wishlist = wishlist;
       this.filmId = filmId;
    }
   
    public Integer getWishItemsId() {
        return this.wishItemsId;
    }
    
    public void setWishItemsId(Integer wishItemsId) {
        this.wishItemsId = wishItemsId;
    }
    public Wishlist getWishlist() {
        return this.wishlist;
    }
    
    public void setWishlist(Wishlist wishlist) {
        this.wishlist = wishlist;
    }
    public short getFilmId() {
        return this.filmId;
    }
    
    public void setFilmId(short filmId) {
        this.filmId = filmId;
    }




}


